# Generated by Django 3.1.4 on 2021-02-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='default.jpg', upload_to='blog_covers'),
        ),
    ]
